[package]
name = "redb-slowdown"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.2", features = ["derive"] }
env_logger = "0.9.0"
lmdb-rkv = "0.14.0"
log = "0.4.14"
redb = { version = "0.0.5", git = "https://github.com/cberner/redb.git" }
